blank_issues_enabled: false
contact_links:
  - name: 🗣️ Ask question
    url: https://github.com/CarbonPackages/Carbon.PreviewModeButton/discussions/new/choose
    about: Please ask and answer questions in discussions
